### ISSUE TITLE
Page keeps loading when no file is chosen

### ISSUE THREAD

**Issue by silvs110** [padaiyal/sanitizer#12]
- [ ] <b>Description</b>
   Page keeps loading when no file is chosen if there was a file that was sanitized previously <br>
- [ ] <b>Affected platforms</b>
All
- [ ] <b>Reproduction steps</b>
     1. Choose a valid HAR file to sanitize
     2. Click on Choose File again
     3. Close window that opened to cancel operation
     4. Page will appear to be loading even if there's no file selected
- [ ] <b>Expected behavior</b>
   If no file is chosen the spinner should not be visible.
- [ ] <b>Screenshots</b>
![image](https://github.com/padaiyal/sanitizer/assets/24996365/6cb86126-b5f9-4f15-8ade-fa2ed57e2743)
- [ ] <b>Additional information</b>

**Comment by the-c0d3br34k3r** [comment]
After replacing the JS sanitization code to Go WASM, this bug still exists. The grey portion in the screenshot isn't shown, but the Go WASM code exits when no file is chosen and the file input dialog is closed. This prevents any other file from being loaded and sanitized. Work around is to refresh the page so that the Go WASM code loads again.
